[package]
name = "play_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[bin]]
name = "api_server"

[dev-dependencies]
reqwest = "0.11"
